# Generated by Django 6.0.2 on 2026-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='friends',
            field=models.TextField(default='Информация отсутсвует'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hobbies',
            field=models.TextField(default='Информация отсутсвует'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='relatives',
            field=models.TextField(default='Информация отсутсвует'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='wishes',
            field=models.TextField(default='Информация отсутсвует'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='zodiak',
            field=models.TextField(default='Информация отсутсвует'),
        ),
    ]
