# Generated by Django 6.0.2 on 2026-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutme_friends_aboutme_hobbies_aboutme_relatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='photo_friends',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
