# Generated by Django 6.0.2 on 2026-02-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutme_photo_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.CreateModel(
            name='SchoolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='school/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery', to='main.school')),
            ],
        ),
    ]
