# Generated by Django 6.0.2 on 2026-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_school_photos_schoolphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolphoto',
            name='video',
            field=models.FileField(blank=True, help_text='Поддерживает .mp4, .webm, .ogg', null=True, upload_to='school/videos/'),
        ),
        migrations.AlterField(
            model_name='schoolphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
    ]
