# Generated by Django 6.0.2 on 2026-02-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schoolphoto_video_alter_schoolphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
