# Generated by Django 6.0.2 on 2026-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutme_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='anthem',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Гимн школы'),
        ),
    ]
